apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql-database
spec:
  selector:
    matchLabels:
      component: database 
  template:
    metadata:
      labels:
        component: database
    spec:
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: mysql-database
          image: mysql:5.7
          volumeMounts:
            - mountPath: /home/pankaj/Projects/PHP-Docker/database-storage
              name: database
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"