apiVersion: v1 
kind: PersistentVolumeClaim 

metadata:
  name: database-persistent-volume-claim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  # local:
  #   path: /home/pankaj/Projects/PHP-Docker/database-storage