apiVersion: apps/v1

kind: Deployment

metadata:
   name: php-blogweb
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: php-blog
          image: pankaj349/php-blog
          ports:
            - containerPort: 80

